name: Issue-PR Link
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    name: Link PR to Issue
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.0
        with:
          repo-token: ${{ secrets.TOKEN }}
          branch-prefix: 'issue-'
          resolve: true
 
